# fly.toml app configuration file generated for tee-time-checker on 2026-06-01T23:55:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tee-time-checker'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'tee_time_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
